"""New tables modifications

Revision ID: 51ce5103f0da
Revises: 25c9d72c7e0b
Create Date: 2024-01-24 14:56:41.410999

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '51ce5103f0da'
down_revision: Union[str, None] = '25c9d72c7e0b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alcadas_cliente', sa.Column('active', sa.Boolean(), nullable=True))
    op.add_column('alcadas_cliente', sa.Column('data_criacao', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('aprovadores_cliente', sa.Column('active', sa.Boolean(), nullable=True))
    op.add_column('aprovadores_cliente', sa.Column('data_criacao', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('limites_proposta', sa.Column('active', sa.Boolean(), nullable=True))
    op.add_column('limites_proposta', sa.Column('data_criacao', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('observacoes_proposta', sa.Column('active', sa.Boolean(), nullable=True))
    op.add_column('observacoes_proposta', sa.Column('data_criacao', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('propostas_contraparte', sa.Column('active', sa.Boolean(), nullable=True))
    op.add_column('propostas_contraparte', sa.Column('data_criacao', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('tipos_rating_cliente', sa.Column('active', sa.Boolean(), nullable=True))
    op.add_column('tipos_rating_cliente', sa.Column('data_criacao', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tipos_rating_cliente', 'data_criacao')
    op.drop_column('tipos_rating_cliente', 'active')
    op.drop_column('propostas_contraparte', 'data_criacao')
    op.drop_column('propostas_contraparte', 'active')
    op.drop_column('observacoes_proposta', 'data_criacao')
    op.drop_column('observacoes_proposta', 'active')
    op.drop_column('limites_proposta', 'data_criacao')
    op.drop_column('limites_proposta', 'active')
    op.drop_column('aprovadores_cliente', 'data_criacao')
    op.drop_column('aprovadores_cliente', 'active')
    op.drop_column('alcadas_cliente', 'data_criacao')
    op.drop_column('alcadas_cliente', 'active')
    # ### end Alembic commands ###
